### ISSUE TITLE
Command "black" not found. Try 'pip install black'.

### ISSUE THREAD

**Issue by Tinche** [joslarson/black-vscode#4]
Is what I get when I try to Format Document. But I have a virtualenv selected, and Black *is* installed in that virtualenv (I can run it manually).

(v 1.2.0)

**Comment by joslarson** [comment]
@Tinche When you say "selected" do you mean you do you have the `python.pythonPath` setting set to your virtualenv's version of python?

**Comment by Tinche** [comment]
I mean in the lower left corner, the proper virtualenv is selected and displayed :)

**Comment by joslarson** [comment]
When you click on that status bar item, what is shown in the  greyed out text of the popup (like the one below)?

![image](https://user-images.githubusercontent.com/3181232/37781845-308ac83a-2db7-11e8-97d2-88b5e8286312.png)

It shows the the path, if one is set, to the version of Python that is being used.

So in my case, if I have black installed in the currently selected virtualenv, I should be able to run `/Users/brojoe/.pyenv/versions/3.6.2/bin/python -m black --help` from the command line and see black's help message print out.

Can you try that and let me know the outcome? Thanks :)

**Comment by Tinche** [comment]
<img width="1440" alt="screen shot 2018-03-22 at 17 03 31" src="https://user-images.githubusercontent.com/1909233/37782426-20ded9bc-2df3-11e8-9d3b-13147837fea3.png">
<img width="811" alt="screen shot 2018-03-22 at 17 04 02" src="https://user-images.githubusercontent.com/1909233/37782445-2abb4b5a-2df3-11e8-8d28-41230aec485d.png">

Hope it helps :)

Totally willing to run debugging commands if you need it

**Comment by joslarson** [comment]
Ah, it's a relative path. I don't think I accounted for that. Can you check and see if setting it to an absolute path works for you as a stop gap?

**Comment by Tinche** [comment]
Yeah, setting it to an absolute path in my workspace settings works. :)

**Comment by joslarson** [comment]
Okay, I'll look into making relative paths work. Thanks :)

**Comment by Tinche** [comment]
Thanks a lot!

**Comment by joslarson** [comment]
@Tinche I just published v1.2.1 which adds support for relative `python.pythonPath` and `black.path` settings. Thanks for the feedback 👍

**Comment by Tinche** [comment]
Thanks a bunch!

**Comment by Tinche** [comment]
Bad news, updating to 1.2.1 didn't fix the issue :(

If it's any additional help, the way I run VS Code is I type "code ." while having the virtualenv active in my terminal.

**Comment by Tinche** [comment]
I can run any additional debug steps or commands if you need me to.

**Comment by joslarson** [comment]
Okay, let's dig into this a bit more. I just published v1.2.2 which has some new debugging features. Make sure you've got the newest extension version installed and set the `black.debug` setting to true. That will output some debug info with what command is actually being run underneath as well as resulting errors. Can you set that up and let me know what debug output you're getting when you try and format something?

**Comment by Tinche** [comment]
```
Failed to format: "black" command not found.
Command "${workspaceFolder}/.venv-cpython3.6/bin/python -m black -l 79 -" resulted in an exit code of 127.
Error: Command failed: ${workspaceFolder}/.venv-cpython3.6/bin/python -m black -l 79 -
/bin/sh: /.venv-cpython3.6/bin/python: No such file or directory
```
Hm, it's not expanding ${workspaceFolder}?

**Comment by joslarson** [comment]
@Tinche I definitely was not handling that either. Thanks for the heads up. I just pushed v1.3.1 which should give you what you're after. I'm going to close this again. But if you're still having issues, just let me know and I'll reopen it again :)

**Comment by Tinche** [comment]
It works now, thanks!
